version: '3.8'

services:
  nuxeo:
    image: wcl/nuxeo
    container_name: nuxeo
    ports:
      - 8080:8080
      - 5005:8787
    volumes:
      - ${PWD}/data:/var/lib/nuxeo/data
      - ${PWD}/nuxeolog:/var/log/nuxeo
      - ${PWD}/mysql/nuxeo.defaults:/opt/nuxeo/server/templates/mysql/nuxeo.defaults
    environment:
      - NUXEO_DATA=/var/lib/nuxeo/data
      - NUXEO_DB_TYPE=mysql
      - NUXEO_ES_HOSTS=http://elasticsearch:9200
      - NUXEO_ES_INDEX_NAME=nuxeo
      - NUXEO_ES_REPLICAS=0
      - NUXEO_ES_SHARDS=1
      - NUXEO_TEMPLATES=sdk,drive
      - NUXEO_URL=http://nuxeo.wclsolution.com/nuxeo
      - NUXEO_LOG=/var/log/nuxeo
      - NUXEO_WORKFLOW_URL=http://docpal-workflow:8085
      - NUXEO_FORCE_CONF=true
    networks:
      - wcl-network
    restart: always

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - wcl-network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    command: ["--log_bin_trust_function_creators=1"]
    security_opt:
      - seccomp:unconfined
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
      - MYSQL_USER=nuxeo
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nuxeo
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
      - ${PWD}/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - wcl-network
    restart: always

  elasticsearch:
    image: elasticsearch:6.5.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - wcl-network
    restart: always

  multitool:
    image: praqma/network-multitool
    networks:
      - wcl-network
    restart: always

volumes:
  mysql:
  mysql_config:
  elastic:

networks:
  wcl-network:
    name: wcl-network-1